[build-system]
requires = ['setuptools', 'setuptools-scm']
build-backend = 'setuptools.build_meta'

[project]
name = 'doopass'
version = '2.3'
authors = [
  { name='Michael Nikishov', email='doopath@gmail.com' },
]
description = 'Crossplatform TUI password manager written in python'
readme = 'README.md'
requires-python = '>=3.11'
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: GNU General Public License (GPL)',
    'Operating System :: OS Independent',
]

dependencies = [
    'bleach==6.0.0',
    'build==0.10.0',
    'certifi==2022.12.7',
    'cffi==1.15.1',
    'charset-normalizer==3.0.1',
    'click==8.1.3',
    'colorama==0.4.6',
    'cryptography==39.0.1',
    'docutils==0.19',
    'idna==3.4',
    'importlib-metadata==4.13.0',
    'jaraco.classes==3.2.3',
    'keyring==23.13.1',
    'markdown-it-py==2.1.0',
    'mdurl==0.1.2',
    'more-itertools==9.0.0',
    'nanoid==2.0.0',
    'packaging==23.0',
    'pkginfo==1.9.6',
    'pycparser==2.21',
    'Pygments==2.14.0',
    'pyperclip==1.8.2',
    'pyproject_hooks==1.0.0',
    'pywin32-ctypes==0.2.0',
    'readme-renderer==37.3',
    'requests==2.28.2',
    'requests-toolbelt==0.10.1',
    'rfc3986==2.0.0',
    'rich==13.3.1',
    'six==1.16.0',
    'textual==0.10.1',
    'twine==4.0.2',
    'urllib3==1.26.14',
    'webencodings==0.5.1',
    'zipp==3.13.0',
]

[tool.setuptools.packages.find]
where = ['.']
include = ['doopass', 'doopass.src', 'assets']

[tool.setuptools.package-data]
'*' = ['*.css', '*.png']

[project.scripts]
doopass = 'doopass.doopass:main'

[project.urls]
'Homepage' = 'https://github.com/doopath/PasswordManager'