# Generated by Django 5.0.2 on 2024-03-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='User',
        ),
    ]
