# Generated by Django 5.0.2 on 2024-05-19 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0002_alter_storage_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doopass.user')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doopass.storage')),
            ],
        ),
    ]
