# Generated by Django 5.0.2 on 2024-05-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0003_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='content',
            field=models.CharField(default=''),
        ),
    ]
