# Generated by Django 5.0.2 on 2024-05-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0003_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='content',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doopass.user'),
        ),
    ]
