# Generated by Django 5.0.2 on 2024-05-22 17:51

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0003_alter_user_managers_alter_backup_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(validators=[django.contrib.auth.password_validation.validate_password]),
        ),
    ]
