# Generated by Django 5.0.2 on 2024-05-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
