# Generated by Django 5.0.2 on 2024-05-19 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0005_alter_storage_content_alter_storage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doopass.user'),
        ),
    ]
