# Generated by Django 5.0.2 on 2024-05-20 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0006_alter_storage_name_alter_storage_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='data',
        ),
        migrations.AddField(
            model_name='backup',
            name='content',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='backup',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
