# Generated by Django 5.0.2 on 2024-05-22 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0007_alter_backup_owner_alter_backup_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
