# Generated by Django 5.0.2 on 2024-05-22 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0008_alter_storage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
