# Generated by Django 5.0.2 on 2024-05-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0009_alter_storage_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='name',
            field=models.CharField(default='My Storage', max_length=255),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(default='My Storage', max_length=255),
        ),
    ]
