# Generated by Django 5.0.2 on 2024-05-23 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0014_alter_backup_content_alter_backup_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backup',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doopass.storage'),
        ),
    ]
