# Generated by Django 5.0.2 on 2024-05-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0015_alter_backup_owner_alter_backup_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='storage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='doopass.storage'),
        ),
    ]
