# Generated by Django 5.0.2 on 2024-05-23 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doopass', '0016_alter_backup_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
